version: '3.8'

services:
  # Ollama service for the AI model
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  # n8n service for workflow automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=n8n
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - NODE_ENV=production
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped

  # API proxy service
  api-proxy:
    build:
      context: ./api-proxy
      dockerfile: Dockerfile
    container_name: api-proxy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - N8N_URL=http://n8n:5678/webhook
      - RESEARCH_WEBHOOK=process-research
      - IMPLEMENT_WEBHOOK=process-implementation
    depends_on:
      - n8n
    restart: unless-stopped

volumes:
  ollama-data:
  n8n-data: