version: '3.8'

services:
  # TurboForge API Proxy
  api-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turboforge-api-proxy
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      # External services - these should point to your separately deployed instances
      - N8N_URL=${N8N_URL}
      - RESEARCH_WEBHOOK=${RESEARCH_WEBHOOK:-process-research}
      - IMPLEMENT_WEBHOOK=${IMPLEMENT_WEBHOOK:-process-implementation}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-turboforge-architect}
      - SERVICENOW_INSTANCE=${SERVICENOW_INSTANCE}
      # Security
      - API_KEY=${API_KEY}
      - ENABLE_API_KEY_AUTH=${ENABLE_API_KEY_AUTH:-false}
      # Other settings
      - OPERATION_EXPIRY_HOURS=${OPERATION_EXPIRY_HOURS:-24}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:3000}
    networks:
      - api-proxy-network

networks:
  api-proxy-network:
    driver: bridge